---
- name: "clone the account project"
  become_user: "{{hosting_username}}"
  include: "roles/common/tasks/clone-system.yml"
  vars:
    repo_base_url: "{{hspc_repo_base}}"
    repo_name: "{{account_server_project_repo_name}}"
    repo_branch: "{{account_server_project_repo_branch}}"
    target_base_folder: "{{hosting_user_home}}"

- name: "install the account app"
  become_user: "{{hosting_username}}"
  shell: "npm install"
  args:
      chdir: "{{account_server_project_folder}}/"

- name: "configure account service"
  template:
    src: "account.service.j2"
    dest: "/etc/systemd/system/account.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "enable account service"
  shell: "systemctl enable account.service"

- name: "reload systemd daemon"
  shell: "systemctl daemon-reload"

- name: "start account"
  service:
    name: "account"
    state: "started"

- name: "verify account is available internally"
  become_user: "{{hosting_username}}"
  wait_for:
    host: "localhost"
    port: "{{account_server_port}}"

- name: "configure nginx (account)"
  template:
    src: "account.j2"
    dest: "/etc/nginx/sites-enabled/account"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - restart nginx

- meta: flush_handlers

- name: "verify account is available externally"
  become_user: "{{hosting_username}}"
  wait_for:
    host: "{{account_server_host}}"
    port: "{{account_server_external_port}}"

- meta: flush_handlers
