---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/{{patient_picker_project_name}}"

- name: "check out {{patient_picker_name}} project"
  become_user: "{{hosting_username}}"
  git: repo={{hspc_repo_base}}/{{patient_picker_project_name}}.git
       version={{patient_picker_project_version}}
       dest={{patient_picker_project_home}}
       update={{update_repositories}}
       force=yes

- name: "install system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "{{patient_picker_name}}"
    service_definition_file: "{{common_service_template}}"
    service_start_command: "{{patient_picker_server_start_command}}"
    service_working_dir: "{{patient_picker_project_home}}"
    gateway_definition_file: "{{common_nginx_gateway_template}}"
    internal_port: "{{patient_picker_server_internal_port}}"
    external_host: "{{patient_picker_server_external_host}}"
    external_port: "{{patient_picker_server_external_port}}"
