---
- hosts: all
  become: yes
  vars_files:
    - roles/common/defaults/main.yml
    - roles/linux/defaults/main.yml
    - roles/api/defaults/main.yml
    - roles/auth/defaults/main.yml
    - roles/messaging/defaults/main.yml
  roles:
    - api_stu3_v3
