---
- hosts: all:!prod.hspconsortium.org
  become: yes
  vars_files:
    - settings.yml
  roles:
    - api_stu3_server

- hosts: prod.hspconsortium.org
  become: yes
  vars_files:
    - settings.yml
  roles:
    - { role: api_stu3_server, skip-tags: ["drop-database"] }
