---
# Machine
hosting_username: "hspc"
hosting_userpass: "nopass"
hosting_user_home: "/home/{{hosting_username}}"
java_home: "/usr/lib/jvm/java-8-openjdk-amd64/jre"
jetty_download_url: "http://central.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.3.6.v20151106/jetty-runner-9.3.6.v20151106.jar"
max_upload_size: "5M"
nginx_home: "/etc/nginx"
fhir_home: "/home/fhir"
certificate_truststore_alias: "hspc"

# Hosting
http_protocol: "{{'https' if use_secure_http else 'http'}}"

# Database configuration
#mysql_host: "{{services_host}}"
mysql_privilage: "*.*:ALL,GRANT"
mysql_connect_host: "%"

snapshot_repository_url: "https://oss.sonatype.org/content/repositories/snapshots"
release_repository_url: "https://repo1.maven.org/maven2/"

# API_STU3 Artifact
api_stu3_server_artifact_group_id: "org.hspconsortium.reference"
api_stu3_server_artifact_artifact_id: "hspc-reference-api-webapp-multitenant"
api_stu3_server_artifact_version: "1.5.2"
api_stu3_server_artifact_packaging: "jar"
#api_stu3_server_artifact_repository_url: "https://oss.sonatype.org/content/repositories/snapshots"
api_stu3_server_artifact_repository_url: "{{release_repository_url}}"

# API_STU3 Database
api_stu3_schema_version: 4
api_stu3_server_sandbox: "hspc{{api_stu3_schema_version}}"
api_stu3_server_database: "hspc_{{api_stu3_schema_version}}_{{api_stu3_server_sandbox}}"

# API_STU3 Host
api_stu3_server_internal_host: "localhost"
api_stu3_server_internal_port: "8074"
api_server_default_sandbox_url: "{{api_stu3_server_external_url}}/{{api_stu3_server_sandbox}}/data"

# Auth Artifact
auth_server_artifact_group_id: "org.hspconsortium.reference"
auth_server_artifact_artifact_id: "hspc-reference-auth-server-firebase-webapp"
auth_server_artifact_version: "1.6-SNAPSHOT"
auth_server_artifact_packaging: "war"
auth_server_artifact_repository_url: "{{snapshot_repository_url}}"

# Auth Database
auth_server_mysql_host: "localhost"
auth_server_database: "oic"

# Auth Host
auth_server_internal_host: "localhost"
auth_server_internal_port: "8060"

# Messaging Artifact
messaging_server_artifact_group_id: "org.hspconsortium.reference"
messaging_server_artifact_artifact_id: "hspc-reference-messaging"
messaging_server_artifact_version: "1.3.0-SNAPSHOT"
messaging_server_artifact_packaging: "jar"
messaging_server_artifact_repository_url: "{{snapshot_repository_url}}"

# Messaging Host
messaging_server_internal_host: "localhost"
messaging_server_internal_port: "8091"

# Account
account_server_internal_host: "localhost"
account_server_internal_port: "8065"
account_accountLoginPage: "{{account_server_external_url}}"
account_accountLogoutPage: "{{account_server_external_url}}/logout"

# Sandman Artifact
sandman_server_artifact_group_id: "org.hspconsortium.sandbox"
sandman_server_artifact_artifact_id: "hspc-sandbox-manager"
sandman_server_artifact_version: "1.6-SNAPSHOT"
sandman_server_artifact_packaging: "war"
sandman_server_artifact_repository_url: "{{snapshot_repository_url}}"

# Sandman Database
sandman_server_database: "sandman"

# Sandman Host
sandman_server_internal_host: "localhost"
sandman_server_internal_port: "8080"
sandman_server_api_v1_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v3_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v4_url: "{{api_stu3_server_external_url}}"
sandman_server_default_sandbox_creator_roles: ADMIN,MANAGE_USERS,MANAGE_DATA
sandman_server_default_system_roles: USER,CREATE_SANDBOX
sandman_server_default_private_sandbox_roles: USER,MANAGE_USERS,MANAGE_DATA
sandman_server_default_sandbox_visibility: PRIVATE
sandman_server_default_public_sandbox_roles: USER
