---
# Machine
hosting_username: "hspc"
hosting_userpass: "nopass"
hosting_user_home: "/home/{{hosting_username}}"
java_home: "/usr/lib/jvm/java-8-openjdk-amd64/jre"
keystore_password: "changeme"
jetty_download_url: "http://central.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.3.6.v20151106/jetty-runner-9.3.6.v20151106.jar"
max_upload_size: "5M"
nginx_home: "/etc/nginx"
fhir_home: "/home/fhir"

# Hosting
use_secure_http: false
http_protocol: "{{'https' if use_secure_http else 'http'}}"
certificate_crt_filename: "self-signed-certificate.crt"
certificate_key_filename: "self-signed-certificate.key"

# Database configuration
#mysql_host: "{{services_host}}"
mysql_username: "fhir"
mysql_password: "password"
mysql_privilage: "*.*:ALL,GRANT"
mysql_connect_host: "%"

# API_STU3 Artifact
api_stu3_server_artifact_group_id: "org.hspconsortium.reference"
api_stu3_server_artifact_artifact_id: "hspc-reference-api-webapp-multitenant"
api_stu3_server_artifact_version: "1.5.2-SNAPSHOT"
api_stu3_server_artifact_packaging: "jar"
api_stu3_server_artifact_location: "{{m2_repo_folder}}/org/hspconsortium/reference/{{api_stu3_server_artifact_artifact_id}}/{{api_stu3_server_artifact_version}}/{{api_stu3_server_artifact_artifact_id}}-{{api_stu3_server_artifact_version}}.{{api_stu3_server_artifact_packaging}}"

# API_STU3 Database
api_stu3_schema_version: 4
api_stu3_server_sandbox: "hspc{{api_stu3_schema_version}}"
api_stu3_server_database: "hspc_{{api_stu3_schema_version}}_{{api_stu3_server_sandbox}}"

# API_STU3 Host
api_stu3_server_internal_host: "localhost"
api_stu3_server_internal_port: "8074"
api_stu3_server_external_host: "localhost"
api_stu3_server_external_port: "9074"
api_stu3_server_initial_memory: 128M
api_stu3_server_max_memory: 256M

# Auth Host
auth_server_internal_host: "localhost"
auth_server_internal_port: "8060"
auth_server_external_host: "localhost"
auth_server_external_port: "9060"
auth_server_initial_memory: 128M
auth_server_max_memory: 256M

# Messaging Host
messaging_server_internal_host: "localhost"
messaging_server_internal_port: "8060"
messaging_server_external_host: "localhost"
messaging_server_external_port: "9060"
messaging_server_initial_memory: 128M
messaging_server_max_memory: 256M

# Service Dependencies
api_stu3_server_url: "{{http_protocol}}://{{api_stu3_server_external_host}}:{{api_stu3_server_external_port}}"
auth_server_url: "{{http_protocol}}://{{auth_server_external_host}}:{{auth_server_external_port}}"
messaging_server_url: "{{http_protocol}}://{{messaging_server_external_host}}:{{messaging_server_external_port}}"
