---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/{{api_name}}"

- name: "download the api webapp"
  become_user: "{{hosting_username}}"
  maven_artifact:
    group_id: "{{api_server_artifact_group_id}}"
    artifact_id: "{{api_server_artifact_artifact_id}}"
    version: "{{api_server_artifact_version}}"
    extension: "{{api_server_artifact_packaging}}"
    repository_url: "{{api_server_artifact_repository_url}}"
    dest: "{{hosting_user_home}}/{{api_name}}/{{api_server_artifact_artifact_id}}-{{api_server_artifact_version}}.{{api_server_artifact_packaging}}"
