---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/{{messaging_name}}"
    - "{{hosting_user_home}}/{{messaging_name}}/mysql"

- name: "download the {{messaging_name}} webapp"
  become_user: "{{hosting_username}}"
  maven_artifact:
    group_id: "{{messaging_server_artifact_group_id}}"
    artifact_id: "{{messaging_server_artifact_artifact_id}}"
    version: "{{messaging_server_artifact_version}}"
    extension: "{{messaging_server_artifact_packaging}}"
    repository_url: "{{messaging_server_artifact_repository_url}}"
    dest: "{{hosting_user_home}}/{{messaging_name}}/{{messaging_server_artifact_artifact_id}}-{{messaging_server_artifact_version}}.{{messaging_server_artifact_packaging}}"

- name: "install {{messaging_name}} system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "{{messaging_name}}"
    service_definition_file: "{{common_service_template}}"
    service_start_command: "{{messaging_server_start_command}}"
    service_working_dir: "{{hosting_user_home}}/{{messaging_name}}"
    gateway_definition_file: "{{common_nginx_gateway_template}}"
    internal_port: "{{messaging_server_internal_port}}"
    external_host: "{{messaging_server_external_host}}"
    external_port: "{{messaging_server_external_port}}"
