---
# metadata
auth_name: "auth"

# vcs project info

# artifact info
auth_server_artifact_group_id: "org.hspconsortium.reference"
auth_server_artifact_artifact_id: "hspc-reference-auth-server-firebase-webapp"
auth_server_artifact_version: "1.6.2"
auth_server_artifact_packaging: "war"
auth_server_artifact_repository_url: "{{release_repository_url}}"

# hosting info
auth_server_internal_port: "8060"
auth_server_external_url: "{{'https' if use_secure_http else 'http'}}://{{auth_server_external_host}}{{(':'+auth_server_external_port|string) if auth_server_external_port|int not in (80,443) else ''}}"
auth_server_start_command: |
  {{java_home}}/bin/java \
  -DXms{{auth_server_initial_memory}} \
  -DXmx{{auth_server_max_memory}} \
  -Djetty.port={{auth_server_internal_port}} \
  -Djetty.host=localhost \
  -Dspring.profiles.active=production \
  -Doidc.datasource.mysql.url=jdbc:mysql://{{auth_server_mysql_host}}:{{mysql_port}}/{{auth_server_database}} \
  -Doidc.datasource.mysql.username={{mysql_username}} \
  -Doidc.datasource.mysql.password={{mysql_password}} \
  -Doidc.issuer={{auth_server_external_url}} \
  -Dhspc.platform.persona.oauthUserLoginEndpointURL={{auth_server_external_url}}/j_spring_security_check \
  -DCONTEXT_FHIR_ENDPOINT={{auth_server_CONTEXT_FHIR_ENDPOINT}} \
  -DCONTEXT_RESOLVE_ENDPOINT={{patient_picker_server_external_url}} \
  -Dhspc.platform.jwt.key={{hspc_platform_jwt_key}} \
  -Dhspc.platform.sandbox.host={{sandman_server_external_url}} \
  -Dhspc.platform.persona.cookieDomain={{auth_server_persona_cookie_domain}} \
  -Dhspc.platform.firebase.projectName={{account_projectId}} \
  -Dhspc.platform.firebase.databaseUrl={{account_firebase_database_url}} \
  -Dhspc.platform.accountLoginPage={{account_accountLoginPage}} \
  -Dhspc.platform.accountLogoutPage={{account_accountLogoutPage}} \
  -jar {{hosting_user_home}}/{{jetty_runner_artifact_artifact_id}}-{{jetty_runner_artifact_version}}.{{jetty_runner_artifact_packaging}} \
  --config {{hosting_user_home}}/jetty.xml \
  {{auth_server_artifact_artifact_id}}-{{auth_server_artifact_version}}.war

# app settings
auth_server_mysql_host: "localhost"
auth_server_database: "oic"
