---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/{{bilirubin_risk_chart_project_name}}"

- name: "check out {{bilirubin_risk_chart_name}} project"
  become_user: "{{hosting_username}}"
  git: repo={{hspc_repo_base}}/{{bilirubin_risk_chart_project_name}}.git
       version={{bilirubin_risk_chart_project_version}}
       dest={{bilirubin_risk_chart_project_home}}
       update={{update_repositories}}
       force=yes

- name: "install system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "{{bilirubin_risk_chart_name}}"
    service_definition_file: "{{common_service_template}}"
    service_start_command: "{{bilirubin_risk_chart_server_start_command}}"
    service_working_dir: "{{bilirubin_risk_chart_project_home}}"
    gateway_definition_file: "{{common_nginx_gateway_template}}"
    internal_port: "{{bilirubin_risk_chart_server_internal_port}}"
    external_host: "{{bilirubin_risk_chart_server_external_host}}"
    external_port: "{{bilirubin_risk_chart_server_external_port}}"
