---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/bilirubin_risk_chart"

# todo replace this with a release through nexus
# todo change project to be a static webapp
- name: "check out bilirubin_risk_chart project"
  become_user: "{{hosting_username}}"
  shell: chdir="{{hosting_user_home}}/bilirubin_risk_chart"
         git clone https://bitbucket.org/hspconsortium/bilirubin-risk-chart.git
  ignore_errors: yes

- name: "update the bilirubin_risk_chart project"
  become_user: "{{hosting_username}}"
  shell: chdir="{{hosting_user_home}}/bilirubin_risk_chart/bilirubin-risk-chart"
         git fetch && git pull
  ignore_errors: yes

- name: "configure nginx (bilirubin_risk_chart)"
  template:
    src: "bilirubin_risk_chart.j2"
    dest: "/etc/nginx/sites-enabled/bilirubin_risk_chart"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "restart nginx"
  service:
    name: "nginx"
    state: "restarted"

- name: "verify bilirubin_risk_chart is available externally"
  become_user: "{{hosting_username}}"
  wait_for:
    host: "{{bilirubin_risk_chart_server_external_host}}"
    port: "{{bilirubin_risk_chart_server_external_port}}"
