---
- name: "drop the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{hosting_user_home}}/{{account_project_name}}"

- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/{{account_project_name}}"

- name: "check out {{account_name}} project"
  become_user: "{{hosting_username}}"
  git: repo={{hspc_repo_base}}/{{account_project_name}}.git
       version={{account_project_version}}
       dest={{account_project_home}}
       update={{update_repositories}}
       force=yes

- name: "patch the config.js"
  become_user: "{{hosting_username}}"
  template:
    src: "config.js.j2"
    dest: "{{account_project_home}}/src/config/config.js"

- name: "npm install"
  become_user: "{{hosting_username}}"
  shell: chdir="{{account_project_home}}"
         npm install

- name: "npm run build"
  become_user: "{{hosting_username}}"
  shell: chdir="{{account_project_home}}"
         npm run build

- name: "install system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "{{account_name}}"
    service_definition_file: "{{common_service_template}}"
    service_start_command: "{{account_server_start_command}}"
    service_working_dir: "{{account_project_home}}"
    gateway_definition_file: "{{common_nginx_gateway_template}}"
    internal_port: "{{account_server_internal_port}}"
    external_host: "{{account_server_external_host}}"
    external_port: "{{account_server_external_port}}"
