---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/account"

- name: "check out account project"
  become_user: "{{hosting_username}}"
  git: repo={{hspc_repo_base}}/account.git
       version={{account_project_version}}
       dest={{hosting_user_home}}/account/account
       update={{update_repositories}}
       force=yes

- name: "npm install"
  become_user: "{{hosting_username}}"
  shell: chdir="{{hosting_user_home}}/account/account"
         npm install

- name: "npm run build"
  become_user: "{{hosting_username}}"
  shell: chdir="{{hosting_user_home}}/account/account"
         npm run {{account_build_command}}

- name: "install account system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "account"
    service_definition_file: "roles/account/templates/account.service.j2"
    gateway_definition_file: "roles/account/templates/account.j2"
    internal_port: "{{account_server_internal_port}}"
    external_host: "{{account_server_external_host}}"
    external_port: "{{account_server_external_port}}"
