---
- name: "installer profile"
  template:
    src: ".bash_profile.j2"
    dest: "~/.bash_profile"

- name: check custom certificate preconditions
  fail: msg="please define the path to the custom certificates that you would like to use"
  when: use_custom_ssl_certificates and (custom_ssl_certificates_path is not defined)

- name: disable apt update on startup
  service: name=apt-daily.service enabled=no

- name: disable apt update timer
  service: name=apt-daily.timer enabled=no

- name: update aptitude cache
  apt: update_cache=yes
  register: result
  until: result|succeeded
  retries: 10
  delay: 10

- name: install prerequisite packages
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - acl
         - aptitude
         - curl
         - git
         - nginx
         - maven
         - mysql-server
         - openjdk-8-jdk
         - python-psycopg2
         - python-jinja2
         - python-httplib2
         - python-mysqldb
         - python-requests
         - python-pycurl
         - python-pip
         - ssl-cert
         - cron
         - jq
         - python-lxml

- name: upgrade server packages
  apt: upgrade=full

- name: create group
  group: name="{{hosting_username}}"

- name: create user
  user: name="{{hosting_username}}" password="{{hosting_userpass}}" update_password="on_create"
        group="{{hosting_username}}" groups=sudo
        shell=/bin/bash

- name: download jetty-runner
  become_user: "{{hosting_username}}"
  get_url:
          url={{jetty_download_url}}
          dest={{hosting_user_home}}/jetty-runner.jar

- name: config jetty-runner
  copy: src=jetty.xml dest={{hosting_user_home}}/jetty.xml

- name: install nvm
  become_user: "{{hosting_username}}"
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

- name: install node
  become_user: "{{hosting_username}}"
  shell: . ~/.bashrc
         nvm install node

- name: create ssl certificates directory
  when: use_secure_http
  file: path=/etc/nginx/ssl state=directory owner=root group=root mode=0640

- name: generate self-signed ssl certificate
  when: use_secure_http and not use_custom_ssl_certificates
  shell: creates=/etc/nginx/ssl/{{certificate_crt_filename}}
         /bin/echo -e "{{self_signed_certificate_ssl_country}}\n{{self_signed_certificate_ssl_province}}\n{{self_signed_certificate_ssl_locality}}\n{{self_signed_certificate_ssl_organization}}\n{{self_signed_certificate_ssl_division}}\n{{domain_name}}\n{{self_signed_certificate_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/{{certificate_key_filename}} -out /etc/nginx/ssl/{{certificate_crt_filename}}
  notify:
        - restart nginx

- name: copy custom ssl certificates
  when: use_secure_http and use_custom_ssl_certificates
  copy: src="{{custom_ssl_certificates_path}}/{{certificate_crt_filename}}"
        dest=/etc/nginx/ssl/{{certificate_crt_filename}}
  notify:
        - restart nginx

- name: copy custom ssl keys
  when: use_secure_http and use_custom_ssl_certificates
  copy: src="{{custom_ssl_certificates_path}}/{{certificate_key_filename}}"
        dest=/etc/nginx/ssl/{{certificate_key_filename}}
  notify:
        - restart nginx

- name: remove server certificate from truststore
  ignore_errors: yes
  when: use_secure_http and use_custom_ssl_certificates
  shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
           -delete -trustcacerts
           -alias {{certificate_truststore_alias}}
           -file /etc/nginx/ssl/{{certificate_crt_filename}}
           -keystore {{hosting_user_home}}/keystore

- name: import server certificate in truststore
  when: use_secure_http and use_custom_ssl_certificates
  shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
           -importcert -trustcacerts
           -alias {{certificate_truststore_alias}}
           -file /etc/nginx/ssl/{{certificate_crt_filename}}
           -keystore {{hosting_user_home}}/keystore

- name: add www-data user to ssl-cert group
  when: use_secure_http
  user: name=www-data groups=ssl-cert

- name: list private key files
  find:
    paths: "/etc/nginx/ssl"
    patterns:
     - "*.key"
     - "*.pem"
  register: keys

- name: set private key permissions
  when: use_secure_http
  file: path="{{item.path}}" group=ssl-cert mode=640
  with_items: "{{keys.files}}"

- name: clear truststore
  file: name={{hosting_user_home}}/keystore state=absent

- name: initialize truststore
  become_user: "{{hosting_username}}"
  when: use_secure_http
  shell: /bin/echo -e "{{keystore_password}}\n{{keystore_password}}\n\n\n\n\n\n\nyes\n" | keytool
           -genkey -alias {{certificate_truststore_alias}}
           -keystore {{hosting_user_home}}/keystore

- name: configure nginx (default)
  template: src=default.j2 dest=/etc/nginx/sites-enabled/default owner=root group=root mode=0644
  notify:
    - restart nginx

- name: configure nginx (upload.conf)
  template: src=upload.conf.j2 dest=/etc/nginx/conf.d/upload.conf owner=root group=root mode=0644
  notify:
    - restart nginx

- name: Configure MySQL user
  mysql_user: name={{mysql_username}} host={{mysql_connect_host}} password={{mysql_password}} priv={{mysql_privilage}} state=present

- name: Drop annonomous MySQL user
  mysql_user: name='' host={{mysql_connect_host}} state=absent

- meta: flush_handlers
