---
- name: checkout cardiac_risk_app
  become_user: "{{hosting_username}}"
  include: "roles/common/tasks/project-clone-system.yml"
  vars:
    project: "{{cardiac_risk_project_info}}"

- name: checkout bp_centiles_app
  become_user: "{{hosting_username}}"
  include: "roles/common/tasks/project-clone-system.yml"
  vars:
    project: "{{bp_centiles_project_info}}"

- name: checkout growth_chart_app
  become_user: "{{hosting_username}}"
  include: "roles/common/tasks/project-clone-system.yml"
  vars:
    project: "{{growth_chart_project_info}}"

- name: checkout patient_picker_app
  become_user: "{{hosting_username}}"
  include: "roles/common/tasks/project-clone-system.yml"
  vars:
    project: "{{patient_picker_project_info}}"

- name: copy patient_picker_app
  become_user: "{{hosting_username}}"
  shell: |
    mkdir -p {{hosting_user_home_apps}}/static/apps/patient-picker
    cp -r {{patient_picker_project_info.target.folder}}/src/main/webapp/static {{hosting_user_home_apps}}/static/apps/patient-picker
    cp -r {{patient_picker_project_info.target.folder}}/src/main/webapp/index.html {{hosting_user_home_apps}}/static/apps/patient-picker

- name: patch patient_picker_app branding
  become_user: "{{hosting_username}}"
  template: src=branded_text.js.j2
            dest={{hosting_user_home_apps}}/static/apps/patient-picker/static/js/branding/branded_text.js

- name: branding rights
  file: path={{hosting_user_home_apps}}/static/apps/patient-picker/static/js/branding/branded_text.js state=file owner=root group=root mode=0644

- name: configure sample apps to use a common fhir-client
  become_user: "{{hosting_username}}"
  shell: sed -i -e 's/node_modules\/fhirclient\/fhir-client\.js/\.\.\/\.\.\/js\/fhir-client\.js/' {{hosting_user_home_apps}}/static/apps/{{item}}
  with_items:
        - bp-centiles/index.html
        - bp-centiles/launch.html
        - cardiac-risk/index.html
        - cardiac-risk/launch.html
        - growth-chart/index.html
        - growth-chart/launch.html

- name: extract images used in registration
  become_user: "{{hosting_username}}"
  unarchive: src="images.tar" dest="{{hosting_user_home_apps}}/static/"

- name: extract common javascript
  become_user: "{{hosting_username}}"
  unarchive: src="js.tar" dest="{{hosting_user_home_apps}}/static/"

- name: extract common angular
  become_user: "{{hosting_username}}"
  unarchive: src="angular.tar" dest="{{hosting_user_home_apps}}/static/"

- name: extract common bootstrap
  become_user: "{{hosting_username}}"
  unarchive: src="bootstrap.tar" dest="{{hosting_user_home_apps}}/static/"

- name: extract common stylesheets
  become_user: "{{hosting_username}}"
  unarchive: src="stylesheets.tar" dest="{{hosting_user_home_apps}}/static/"

- name: configure nginx (sample apps)
  template: src=nginx_apps.j2 dest=/etc/nginx/sites-enabled/apps owner=root group=root mode=0644
  notify:
    - restart nginx

- meta: flush_handlers

# not working for some reason, getting a 403, but the apps are hosted
#- name: verify app-server is available
#  wait_for: host={{app_server_host}} port={{app_server_port}}
#
