---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file: "path={{item}} state=directory"
  with_items:
    - "{{hosting_user_home}}/nexus"

- name: "install nexus"
  become_user: "{{hosting_username}}"
  unarchive:
    src: "http://download.sonatype.com/nexus/3/latest-unix.tar.gz"
    dest: "{{hosting_user_home}}/nexus"


- name: download jetty-runner
  become_user: "{{hosting_username}}"
  get_url:
          url={{jetty_download_url}}
          dest={{hosting_user_home}}/jetty-runner.jar
