---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file: "path={{item}} state=directory"
  with_items:
    - "{{hosting_user_home}}/nexus"

- name: "download nexus"
  become_user: "{{hosting_username}}"
  shell: wget http://download.sonatype.com/nexus/3/latest-unix.tar.gz

- name: "copy to the service directory"
  become_user: "{{hosting_username}}"
  copy:
    src: "*.tar.gz"
    dest: "{{hosting_user_home}}/nexus"
    remote_src: true

- name: "unpack nexus"
  become_user: "{{hosting_username}}"
  shell: tar -zxvf {{hosting_user_home}}/nexus/*.tar.gz

