---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file: "path={{item}} state=directory"
  with_items:
    - "{{hosting_user_home}}/nexus"

- name: "install nexus"
  become_user: "{{hosting_username}}"
  shell:
    cd {{hosting_user_home}}/nexus
    wget http://download.sonatype.com/nexus/3/latest-unix.tar.gz
    tar -zxvf *.tar.gz

