---

# API_STU3_V2 Database
api_stu3_v2_schema_version: 2
api_stu3_v2_server_sandbox: "hspc{{api_stu3_v2_schema_version}}"
api_stu3_v2_server_database: "hspc_{{api_stu3_v2_schema_version}}_{{api_stu3_v2_server_sandbox}}"
api_stu3_v2_mysql_username: "{{mysql_username}}"
api_stu3_v2_mysql_password: "{{mysql_password}}"
api_stu3_v2_server_internal_port: "8072"
api_stu3_v2_server_external_url: "{{'https' if use_secure_http else 'http'}}://{{api_stu3_v2_server_external_host}}{{(':'+api_stu3_v2_server_external_port|string) if api_stu3_v2_server_external_port|int not in (80,443) else ''}}"
