---
- name: "drop the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{hosting_user_home}}/{{gallery_project_name}}"

- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/{{gallery_project_name}}"
    - "{{hosting_user_home}}/{{gallery_project_name}}/mysql"

- name: "check out {{gallery_name}} project"
  become_user: "{{hosting_username}}"
  git: repo={{hspc_repo_base}}/{{gallery_project_name}}.git
       version={{gallery_project_version}}
       dest={{gallery_project_home}}
       update={{update_repositories}}
       force=yes

- name: "patch the app-gallery.json"
  become_user: "{{hosting_username}}"
  template:
    src: "app-gallery.json.j2"
    dest: "{{gallery_project_home}}/src/js/config/app-gallery.json"

- name: "patch the gallery-apps.json"
  become_user: "{{hosting_username}}"
  template:
    src: "{{gallery_apps_template}}"
    dest: "{{gallery_project_home}}/src/js/config/gallery-apps.json"

- name: "install system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "{{gallery_name}}"
    service_definition_file: "{{common_service_template}}"
    service_start_command: "{{gallery_server_start_command}}"
    service_working_dir: "{{gallery_project_home}}"
    gateway_definition_file: "{{common_nginx_gateway_template}}"
    internal_port: "{{gallery_server_internal_port}}"
    external_host: "{{gallery_server_external_host}}"
    external_port: "{{gallery_server_external_port}}"
