---

# *** Main configuration file for the HSPC Reference Platform Installer ***

# To customize the HSPC stack, you can either edit the settings directly in
# this file or set up custom settings overrides (such as custom_settings.yml)

# The user account that will host the servers. If a user account of this name
# already exists on the system, the installer will not alter its credentials or
# authentication mechanism. If you need to set up actual password authentication,
# userpass needs to be a valid SHA-512 hash.

services_host: "localhost"

hosting_username: "fhir"
hosting_userpass: "nopass"
hosting_user_home: "/home/{{hosting_username}}"
hosting_user_home_projects: "{{hosting_user_home}}/projects"
hosting_user_home_apps: "{{hosting_user_home}}/apps"
hosting_user_home_hspc: "{{hosting_user_home}}/hspc"
m2_repo_folder: "{{hosting_user_home}}/.m2/repository"

top_level_domain: "org"
second_level_domain: "hspconsortium"
additional_subdomains: ""
domain_name: "{{additional_subdomains}}{{second_level_domain}}.{{top_level_domain}}"

# Suppresses selective task execution (set this to true if you would like to
# force the playbook to always rebuild the servers and reload them)
force_rebuild: true

# By default Ansible will update the local copies of the servers code from
# the source repositories. Set this to "no" if you would rather not have the
# repositories updated on each run.
update_repositories: "yes"

# Settigs for Jetty and Oracle Java. You probably won't have to alter these
# unles you are switching to a different version of Jetty or Java
java_home: "/usr/lib/jvm/java-8-openjdk-amd64/jre"
jetty_download_url: "http://central.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.3.6.v20151106/jetty-runner-9.3.6.v20151106.jar"

# Database configuration
mysql_host: "{{services_host}}"
mysql_connect_host: "%"
mysql_endpoint: "{{mysql_host}}:3306"
mysql_root_pass: "password"
mysql_username: "fhir"
mysql_password: "password"
#mysql_privilage: "{{auth_server_database}}.*:ALL/{{sandbox_manager_database}}.*:ALL/*.*:ALL,GRANT"
mysql_privilage: "*.*:ALL,GRANT"
mysql_bind_address: "0.0.0.0"

# Password for the Java keystore used by the authorization server (please change)
keystore_password: "changeme"

# When set to true, https is used
use_secure_http: false

# When setting up SSL security for the various services, these settings will allow you to
# specify your own certificates instead of using self-signed certificates.
# See files/sample-certificates for the names of the certificate files expected by the script
use_custom_ssl_certificates: false
#custom_ssl_certificates_path: examples/certificates

certificate_crt_filename: "self-signed-certificate.crt"
certificate_key_filename: "self-signed-certificate.key"

certificate_truststore_alias: "hspc"

# Self-signed SSL certificates settings (if generating self-signed certificates)
self_signed_certificate_ssl_country: "US"
self_signed_certificate_ssl_province: "UT"
self_signed_certificate_ssl_locality: "Murray"
self_signed_certificate_ssl_organization: "HSPConsortium"
self_signed_certificate_ssl_division: "support"
self_signed_certificate_ssl_email: "support@{{domain_name}}"

# Controls whether HTTP requests on port 80 will be
# redirected to the server's base URLs
http_redirect: true

# Set this to either "open" or "secured" on the primary endpoint /data
fhir_server_security_mode: "secured"
# Set this to either "true" or "false" to allow an open endpoint at /open
fhir_server_allow_open_access: true

# Artifact Repositories
smart_repo_base: "https://github.com/smart-on-fhir"
hspc_repo_base: "https://bitbucket.org/hspconsortium"

# Apps Repositories
app_server_host: "{{services_host}}"
app_server_port: "9093"

cardiac_risk_project_info:
  repo:
    base_url: "{{smart_repo_base}}"
    name: "cardiac-risk-app"
    tag: "v0.1.1"
  target:
    base_folder: "{{hosting_user_home_apps}}/static/apps"
    name: "cardiac-risk"
    folder: "{{hosting_user_home_apps}}/static/apps/cardiac-risk"

bp_centiles_project_info:
  repo:
    base_url: "{{smart_repo_base}}"
    name: "bp-centiles-app"
    tag: "v0.1.2"
  target:
    base_folder: "{{hosting_user_home_apps}}/static/apps"
    name: "bp-centiles"
    folder: "{{hosting_user_home_apps}}/static/apps/bp-centiles"

growth_chart_project_info:
  repo:
    base_url: "{{smart_repo_base}}"
    name: "growth-chart-app"
    tag: "v0.1.2"
  target:
    base_folder: "{{hosting_user_home_apps}}/static/apps"
    name: "growth-chart"
    folder: "{{hosting_user_home_apps}}/static/apps/growth-chart"

# todo get this from a maven release
patient_picker_project_info:
  repo:
    base_url: "{{hspc_repo_base}}"
    name: "patient-picker"
    tag: "1.0"
  target:
    base_folder: "{{hosting_user_home_hspc}}"
    name: "patient-picker"
    folder: "{{hosting_user_home_hspc}}/patient-picker"

sample_patients_project_info:
  repo:
    base_url: "{{smart_repo_base}}"
    name: "sample-patients"
  target:
    base_folder: "{{hosting_user_home_apps}}/static/apps"
    name: "growth-chart"
    folder: "{{hosting_user_home_apps}}/static/apps/growth-chart"

# choose how many sample patients to load in the server or set to 9999 for all of them
include_custom_patients: false
api_dstu2_sample_patients_generator_params: "--id-prefix SMART"

app_server_base: "{{
    'https' if use_secure_http else 'http'}}://{{app_server_host}}{{
    (':'+app_server_port|string) if app_server_port|int not in (80,443) else ''}}"

# Additional parameters for the sample patient generator
sample_patients_generator_params: ""

# API Server client
api_stu3_server_oauth2_clientId: "hspc_resource_server"
api_stu3_server_oauth2_clientSecret: "secret"

# API_STU3 Database
api_stu3_schema_version: 4
api_stu3_server_sandbox: "hspc{{api_stu3_schema_version}}"
api_stu3_server_database: "hspc_{{api_stu3_schema_version}}_{{api_stu3_server_sandbox}}"

# API_STU3 Server
api_stu3_server_host: "{{services_host}}"
api_stu3_server_external_port: "443"
api_stu3_server_port: "8070"
api_stu3_server_url: "http://{{api_stu3_server_host}}:{{api_stu3_server_port}}/"
api_stu3_server_default_sandbox_url: "{{api_stu3_server_url}}/{{api_stu3_server_sandbox}}"
api_stu3_server_default_sandbox_fhir_root_url: "{{api_stu3_server_default_sandbox_url}}/data"

# SandboxManager Server
sandbox_manager_server_host: "{{services_host}}"
sandbox_manager_server_port: "9080"
sandbox_manager_server_internal_host: "{{services_host}}"
sandbox_manager_server_internal_port: "8080"
sandbox_manager_server_context: "/"
sandbox_manager_server_name: "Sandbox Manager server"
sandbox_manager_server_inferred_protocol: "{{'https' if use_secure_http else 'http'}}"
sandbox_manager_server_inferred_port: "{{(':'+sandbox_manager_server_port|string) if sandbox_manager_server_port|int not in (80,443) else ''}}"
sandbox_manager_server_base_url: "{{sandbox_manager_server_inferred_protocol}}://{{sandbox_manager_server_host}}{{sandbox_manager_server_inferred_port}}"
sandbox_manager_server_url: "{{sandbox_manager_server_base_url}}{{sandbox_manager_server_context}}"

# Auth Server
auth_server_host: "{{services_host}}"
auth_server_external_port: "9060"
auth_server_port: "8060"
# requiring two deployments of the auth server
auth_server_context: "/"
auth_server_name: "Authorization Server"
auth_server_inferred_protocol: "{{'https' if use_secure_http else 'http'}}"
auth_server_inferred_port: "{{(':'+auth_server_port|string) if auth_server_port|int not in (80,443) else ''}}"
auth_server_base_url: "{{auth_server_inferred_protocol}}://{{auth_server_host}}{{auth_server_inferred_port}}"
auth_server_url: "{{auth_server_base_url}}{{auth_server_context}}"
auth_server_client: "client"
auth_server_password: "secret"
auth_server_enable_mock_endpoints: true

# Messaging Server
messaging_server_host: "{{services_host}}"
messaging_server_external_port: "9091"
messaging_server_port: "8091"
messaging_server_context: "/"
messaging_server_name: "Messaging Server"
messaging_server_inferred_protocol: "{{'https' if use_secure_http else 'http'}}"
messaging_server_inferred_port: "{{(':'+messaging_server_port|string) if messaging_server_port|int not in (80,443) else ''}}"
messaging_server_base_url: "{{messaging_server_inferred_protocol}}://{{messaging_server_host}}{{messaging_server_inferred_port}}"
messaging_server_url: "{{messaging_server_base_url}}{{messaging_server_context}}"

nginx_home: "/etc/nginx"
fhir_home: "/home/fhir"
installer_user: "vagrant"
installer_user_home: "/home/{{installer_user}}"
installer_home: "{{installer_user_home}}/installer"

user_scripts_home: "{{hosting_user_home}}/scripts"
user_jobs_home: "{{hosting_user_home}}/jobs"
user_jobs_output_home: "{{user_jobs_home}}/output"

enable_aws_snapshot: false
aws_output_format: 'json'
aws_region: "changeme"
aws_access_key_id: "changeme"
aws_secret_access_key: "changeme"
aws_ec2_volume_id: "changeme"

# Maximu size of sample patient data files
max_upload_size: "5M"

#delete below

# Self-signed SSL certificates settings (if generating self-signed certificates)
default_ssl_country: "US"
default_ssl_province: "MA"
default_ssl_locality: "Boston"
default_ssl_organization: "Example Company"
default_ssl_division: "support"
default_ssl_email: "support@{{domain_name}}"
app_server_ssl_country: "{{default_ssl_country}}"
app_server_ssl_province: "{{default_ssl_province}}"
app_server_ssl_locality: "{{default_ssl_locality}}"
app_server_ssl_organization: "{{default_ssl_organization}}"
app_server_ssl_division: "{{default_ssl_division}}"
app_server_ssl_email: "{{default_ssl_email}}"

# LDAP server configuration
ldap_server_organization: "SMART Heathcare IT"
ldap_server_domain: "{{domain_name}}"
ldap_server_host: "{{services_host}}"
ldap_server_port: "10389"
ldap_server_base: "dc={{second_level_domain}},dc={{top_level_domain}}"
ldap_server_uri: "ldap://{{ldap_server_host}}:{{ldap_server_port}}"
ldap_server_admin_password: "sample-password"
ldap_server_account_admin_password: "password"
ldap_server_account_demo_password: "demo"

# Email server account
email_account_description: "Example Account Services"
email_smtp_address: "smtp.example.com"
email_smtp_port: "587"
email_smtp_username: "changeme"
email_smtp_password: "changeme"
email_smtp_password_encrypted: "changeme"
email_admin_address: "changeme@example.com"
email_contact_addresss: "support@example.org"