---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/{{api_stu3_v2_name}}"

# when migrated to the HSPC_4 schema
#- name: "download the api webapp"
#  become_user: "{{hosting_username}}"
#  maven_artifact:
#    group_id: "{{api_server_artifact_group_id}}"
#    artifact_id: "{{api_server_artifact_artifact_id}}"
#    version: "{{api_server_artifact_version}}"
#    extension: "{{api_server_artifact_packaging}}"
#    repository_url: "{{api_server_artifact_repository_url}}"
#    dest: "{{hosting_user_home}}/api/{{api_server_artifact_artifact_id}}-{{api_server_artifact_version}}.{{api_server_artifact_packaging}}"

# workaround due to the HSPC v2 schema
- name: "copy the api-v2-beanstalk.war to the service directory"
  become_user: "{{hosting_username}}"
  copy:
    src: "api-v2-beanstalk.war"
    dest: "{{hosting_user_home}}/{{api_stu3_v2_name}}"

- name: "install {{api_stu3_v2_name}} system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "{{api_stu3_v2_name}}"
    database: "{{api_stu3_v2_server_database}}"
    database_reset: "{{api_stu3_v2_mysql_reset_database}}"
    service_definition_file: "{{common_service_template}}"
    service_start_command: "{{api_stu3_v2_server_start_command}}"
    service_working_dir: "{{hosting_user_home}}/{{api_stu3_v2_name}}"
    gateway_definition_file: "{{common_nginx_gateway_template}}"
    internal_port: "{{api_stu3_v2_server_internal_port}}"
    external_host: "{{api_stu3_v2_server_external_host}}"
    external_port: "{{api_stu3_v2_server_external_port}}"
