---
# metadata
messaging_name: "messaging"

# vcs project info

# artifact info
messaging_server_artifact_group_id: "org.hspconsortium.reference"
messaging_server_artifact_artifact_id: "hspc-reference-messaging"
messaging_server_artifact_version: "1.3.0"
messaging_server_artifact_packaging: "jar"
messaging_server_artifact_repository_url: "{{release_repository_url}}"

# hosting info
messaging_server_internal_port: "8091"
messaging_server_external_url: "{{'https' if use_secure_http else 'http'}}://{{messaging_server_external_host}}{{(':'+messaging_server_external_port|string) if messaging_server_external_port|int not in (80,443) else ''}}"
messaging_server_start_command: |
  {{java_home}}/bin/java \
  -Xms{{messaging_server_initial_memory}} \
  -Xmx{{messaging_server_max_memory}} \
  -Dhspc.reference.api.url={{api_server_default_sandbox_url}} \
  -Dspring.profiles.active={{messaging_profiles}} \
  -Dmail.server.password={{messaging_mail_server_password}} \
  -Dmail.server.username={{messaging_mail_server_username}} \
  -jar {{messaging_server_artifact_artifact_id}}-{{messaging_server_artifact_version}}.{{messaging_server_artifact_packaging}}
